### ISSUE TITLE
Capital P in --scope=@Psychedelic caused an `is not in the npm registry.` on package install

### ISSUE THREAD

**Issue by rckprtr** [Psychedelic/DAB-js#50]
https://github.com/Psychedelic/DAB-js/blob/6737f7fb7a77ebfa37dc8b0dd6f322527d749def/README.md?plain=1#L54

My `.npmrc` was case sensitive and causing an installation issue.  By manual editing my '.npmrc` file to be lowercase `p` I was able to successfully install the package.

Mac OSX Monterey
npm 6.14.4

**Comment by tomiir** [comment]
Hi! Your PR has been merged so I'm closing this issue.
Thanks for the report and fix 🙏 🙏 !
